[package]
description = "Connectivity manager based on reputation"
homepage = "https://substrate.io"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name = "sc-peerset"
version = "6.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-peerset"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.21"
libp2p = "0.50.0"
log = "0.4.17"
serde_json = "1.0.85"
wasm-timer = "0.2"
sc-utils = { version = "5.0.0", path = "../utils" }

[dev-dependencies]
rand = "0.8.5"
