[package]
name = "sc-executor-wasmi"
version = "0.18.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "This crate provides an implementation of `WasmRuntime` that is baked by wasmi."
documentation = "https://docs.rs/sc-executor-wasmi"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.17"
wasmi = "0.13"
sc-allocator = { version = "12.0.0", path = "../../allocator" }
sc-executor-common = { version = "0.18.0", path = "../common" }
sp-runtime-interface = { version = "13.0.0", path = "../../../primitives/runtime-interface" }
sp-wasm-interface = { version = "10.0.0", path = "../../../primitives/wasm-interface" }
