[package]
name = "pallet-election-provider-multi-phase"
version = "15.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "PALLET two phase election providers"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.1.1", default-features = false, features = [
	"derive",
] }
log = { version = "0.4.17", default-features = false }

frame-support = { version = "16.0.0", default-features = false, path = "../support" }
frame-system = { version = "16.0.0", default-features = false, path = "../system" }

sp-io = { version = "17.0.0", default-features = false, path = "../../primitives/io" }
sp-std = { version = "6.0.0", default-features = false, path = "../../primitives/std" }
sp-core = { version = "16.0.0", default-features = false, path = "../../primitives/core" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../../primitives/runtime" }
sp-npos-elections = { version = "14.0.0", default-features = false, path = "../../primitives/npos-elections" }
sp-arithmetic = { version = "12.0.0", default-features = false, path = "../../primitives/arithmetic" }
frame-election-provider-support = { version = "16.0.0", default-features = false, path = "../election-provider-support" }

# Optional imports for benchmarking
frame-benchmarking = { version = "16.0.0", default-features = false, path = "../benchmarking", optional = true }
pallet-election-provider-support-benchmarking = { version = "15.0.0", default-features = false, path = "../election-provider-support/benchmarking", optional = true }
rand = { version = "0.8.5", default-features = false, features = ["alloc", "small_rng"], optional = true }
strum = { version = "0.24.1",  default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
parking_lot = "0.12.1"
rand = "0.8.5"
sp-core = { version = "16.0.0", default-features = false, path = "../../primitives/core" }
sp-io = { version = "17.0.0", path = "../../primitives/io" }
sp-npos-elections = { version = "14.0.0", default-features = false, path = "../../primitives/npos-elections" }
sp-tracing = { version = "8.0.0", path = "../../primitives/tracing" }
pallet-balances = { version = "16.0.0", path = "../balances" }
frame-benchmarking = { version = "16.0.0", path = "../benchmarking" }

[features]
default = ["std"]
std = [
	"pallet-election-provider-support-benchmarking?/std",
	"codec/std",
	"scale-info/std",
	"log/std",

	"frame-support/std",
	"frame-system/std",

	"sp-io/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-npos-elections/std",
	"sp-arithmetic/std",
	"frame-election-provider-support/std",
	"log/std",

	"frame-benchmarking?/std",
	"rand/std",
	"strum/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"rand",
	"strum",
]
try-runtime = ["frame-support/try-runtime"]
