[package]
name = "substrate-frame-rpc-system"
version = "16.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME's system exposed over Substrate RPC"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
futures = "0.3.21"
log = "0.4.17"
frame-system-rpc-runtime-api = { version = "14.0.0", path = "../../../../frame/system/rpc/runtime-api" }
sc-rpc-api = { version = "0.21.0", path = "../../../../client/rpc-api" }
sc-transaction-pool-api = { version = "16.0.0", path = "../../../../client/transaction-pool/api" }
sp-api = { version = "14.0.0", path = "../../../../primitives/api" }
sp-block-builder = { version = "14.0.0", path = "../../../../primitives/block-builder" }
sp-blockchain = { version = "16.0.0", path = "../../../../primitives/blockchain" }
sp-core = { version = "16.0.0", path = "../../../../primitives/core" }
sp-runtime = { version = "18.0.0", path = "../../../../primitives/runtime" }

[dev-dependencies]
sc-transaction-pool = { version = "16.0.0", path = "../../../../client/transaction-pool" }
tokio = "1.22.0"
assert_matches = "1.3.0"
sp-tracing = { version = "8.0.0", path = "../../../../primitives/tracing" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../../test-utils/runtime/client" }
