[package]
name = "pallet-session-benchmarking"
version = "16.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME sessions pallet benchmarking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std_rng"] }
frame-benchmarking = { version = "16.0.0", default-features = false, path = "../../benchmarking" }
frame-support = { version = "16.0.0", default-features = false, path = "../../support" }
frame-system = { version = "16.0.0", default-features = false, path = "../../system" }
pallet-session = { version = "16.0.0", default-features = false, path = "../../session" }
pallet-staking = { version = "16.0.0", default-features = false, path = "../../staking" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../../../primitives/runtime" }
sp-session = { version = "15.0.0", default-features = false, path = "../../../primitives/session" }
sp-std = { version = "6.0.0", default-features = false, path = "../../../primitives/std" }

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }
scale-info = "2.1.1"
frame-election-provider-support = { version = "16.0.0", path = "../../election-provider-support" }
pallet-balances = { version = "16.0.0", path = "../../balances" }
pallet-staking-reward-curve = { version = "4.0.0", path = "../../staking/reward-curve" }
pallet-timestamp = { version = "15.0.0", path = "../../timestamp" }
sp-core = { version = "16.0.0", path = "../../../primitives/core" }
sp-io = { version = "17.0.0", path = "../../../primitives/io" }

[features]
default = ["std"]
std = [
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-session/std",
	"pallet-staking/std",
	"rand/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"pallet-staking/runtime-benchmarks",
]
