[package]
name = "node-cli"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Generic Substrate node implementation in Rust."
build = "build.rs"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
default-run = "substrate"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[badges]
travis-ci = { repository = "paritytech/substrate" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[[bin]]
name = "substrate"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
array-bytes = "4.1"
clap = { version = "4.0.9", features = ["derive"], optional = true }
codec = { package = "parity-scale-codec", version = "3.2.2" }
serde = { version = "1.0.136", features = ["derive"] }
jsonrpsee = { version = "0.16.2", features = ["server"] }
futures = "0.3.21"
log = "0.4.17"
rand = "0.8"

# primitives
sp-authority-discovery = { version = "14.0.0", path = "../../../primitives/authority-discovery" }
sp-consensus-babe = { version = "0.20.0", path = "../../../primitives/consensus/babe" }
grandpa-primitives = { version = "14.0.0", package = "sp-finality-grandpa", path = "../../../primitives/finality-grandpa" }
sp-api = { version = "14.0.0", path = "../../../primitives/api" }
sp-core = { version = "16.0.0", path = "../../../primitives/core" }
sp-runtime = { version = "18.0.0", path = "../../../primitives/runtime" }
sp-timestamp = { version = "14.0.0", path = "../../../primitives/timestamp" }
sp-inherents = { version = "14.0.0", path = "../../../primitives/inherents" }
sp-keyring = { version = "18.0.0", path = "../../../primitives/keyring" }
sp-keystore = { version = "0.22.0", path = "../../../primitives/keystore" }
sp-consensus = { version = "0.20.0", path = "../../../primitives/consensus/common" }
sp-transaction-pool = { version = "14.0.0", path = "../../../primitives/transaction-pool" }
sp-transaction-storage-proof = { version = "14.0.0", path = "../../../primitives/transaction-storage-proof" }
sp-io = { path = "../../../primitives/io" , version = "17.0.0" }

# client dependencies
sc-client-api = { version = "16.0.0", path = "../../../client/api" }
sc-chain-spec = { version = "15.0.0", path = "../../../client/chain-spec" }
sc-consensus = { version = "0.21.0", path = "../../../client/consensus/common" }
sc-transaction-pool = { version = "16.0.0", path = "../../../client/transaction-pool" }
sc-transaction-pool-api = { version = "16.0.0", path = "../../../client/transaction-pool/api" }
sc-network = { version = "0.22.0", path = "../../../client/network" }
sc-network-common = { version = "0.21.0", path = "../../../client/network/common" }
sc-consensus-slots = { version = "0.21.0", path = "../../../client/consensus/slots" }
sc-consensus-babe = { version = "0.22.0", path = "../../../client/consensus/babe" }
grandpa = { version = "0.22.0", package = "sc-finality-grandpa", path = "../../../client/finality-grandpa" }
sc-rpc = { version = "17.0.0", path = "../../../client/rpc" }
sc-basic-authorship = { version = "0.22.0", path = "../../../client/basic-authorship" }
sc-service = { version = "0.23.0", default-features = false, path = "../../../client/service" }
sc-telemetry = { version = "6.0.0", path = "../../../client/telemetry" }
sc-executor = { version = "0.20.0", path = "../../../client/executor" }
sc-authority-discovery = { version = "0.22.0", path = "../../../client/authority-discovery" }
sc-sync-state-rpc = { version = "0.22.0", path = "../../../client/sync-state-rpc" }
sc-sysinfo = { version = "15.0.0", path = "../../../client/sysinfo" }
sc-storage-monitor = { version = "0.4.0", path = "../../../client/storage-monitor" }

# frame dependencies
frame-system = { version = "16.0.0", path = "../../../frame/system" }
frame-system-rpc-runtime-api = { version = "14.0.0", path = "../../../frame/system/rpc/runtime-api" }
pallet-transaction-payment = { version = "16.0.0", path = "../../../frame/transaction-payment" }
pallet-assets = { version = "17.0.0", path = "../../../frame/assets/" }
pallet-asset-tx-payment = { version = "16.0.0", path = "../../../frame/transaction-payment/asset-tx-payment/" }
pallet-im-online = { version = "15.0.0", default-features = false, path = "../../../frame/im-online" }

# node-specific dependencies
kitchensink-runtime = { version = "3.0.0-dev", path = "../runtime" }
node-rpc = { version = "3.0.0-dev", path = "../rpc" }
node-primitives = { version = "2.0.0", path = "../primitives" }
node-executor = { version = "3.0.0-dev", path = "../executor" }

# CLI-specific dependencies
sc-cli = { version = "0.24.0", optional = true, path = "../../../client/cli" }
frame-benchmarking-cli = { version = "20.0.0", optional = true, path = "../../../utils/frame/benchmarking-cli" }
node-inspect = { version = "0.9.0-dev", optional = true, path = "../inspect" }
try-runtime-cli = { version = "0.26.0", optional = true, path = "../../../utils/frame/try-runtime/cli" }
serde_json = "1.0.85"

[dev-dependencies]
sc-keystore = { version = "13.0.0", path = "../../../client/keystore" }
sc-client-db = { version = "0.23.0", path = "../../../client/db" }
sc-consensus = { version = "0.21.0", path = "../../../client/consensus/common" }
sc-consensus-babe = { version = "0.22.0", path = "../../../client/consensus/babe" }
sc-consensus-epochs = { version = "0.21.0", path = "../../../client/consensus/epochs" }
sc-service-test = { version = "2.0.0", path = "../../../client/service/test" }
sc-block-builder = { version = "0.21.0", path = "../../../client/block-builder" }
sp-tracing = { version = "8.0.0", path = "../../../primitives/tracing" }
sp-blockchain = { version = "16.0.0", path = "../../../primitives/blockchain" }
futures = "0.3.21"
tempfile = "3.1.0"
assert_cmd = "2.0.2"
nix = { version = "0.26.1", features = ["signal"] }
serde_json = "1.0"
regex = "1.6.0"
platforms = "2.0"
soketto = "0.7.1"
criterion = { version = "0.4.0", features = ["async_tokio"] }
tokio = { version = "1.22.0", features = ["macros", "time", "parking_lot"] }
tokio-util = { version = "0.7.4", features = ["compat"] }
wait-timeout = "0.2"
substrate-rpc-client = { path = "../../../utils/frame/rpc/client" , version = "0.21.0" }
pallet-timestamp = { version = "15.0.0", path = "../../../frame/timestamp" }

[build-dependencies]
clap = { version = "4.0.9", optional = true }
clap_complete = { version = "4.0.2", optional = true }
node-inspect = { version = "0.9.0-dev", optional = true, path = "../inspect" }
frame-benchmarking-cli = { version = "20.0.0", optional = true, path = "../../../utils/frame/benchmarking-cli" }
substrate-build-script-utils = { version = "4.0.0", optional = true, path = "../../../utils/build-script-utils" }
substrate-frame-cli = { version = "20.0.0", optional = true, path = "../../../utils/frame/frame-utilities-cli" }
try-runtime-cli = { version = "0.26.0", optional = true, path = "../../../utils/frame/try-runtime/cli" }
sc-cli = { version = "0.24.0", path = "../../../client/cli", optional = true }
pallet-balances = { version = "16.0.0", path = "../../../frame/balances" }
sc-storage-monitor = { version = "0.4.0", path = "../../../client/storage-monitor" }

[features]
default = ["cli"]
cli = [
	"node-inspect",
	"sc-cli",
	"frame-benchmarking-cli",
	"substrate-frame-cli",
	"sc-service/rocksdb",
	"clap",
	"clap_complete",
	"substrate-build-script-utils",
	"try-runtime-cli",
]
runtime-benchmarks = [
	"kitchensink-runtime/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks"
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["kitchensink-runtime/try-runtime", "try-runtime-cli/try-runtime"]

[[bench]]
name = "transaction_pool"
harness = false

[[bench]]
name = "block_production"
harness = false
