[package]
name = "sc-consensus-manual-seal"
version = "0.23.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Manual sealing engine for Substrate"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
assert_matches = "1.3.0"
async-trait = "0.1.57"
codec = { package = "parity-scale-codec", version = "3.2.2" }
futures = "0.3.21"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.11.0", path = "../../../utils/prometheus" }
sc-client-api = { version = "16.0.0", path = "../../api" }
sc-consensus = { version = "0.21.0", path = "../../consensus/common" }
sc-consensus-aura = { version = "0.22.0", path = "../../consensus/aura" }
sc-consensus-babe = { version = "0.22.0", path = "../../consensus/babe" }
sc-consensus-epochs = { version = "0.21.0", path = "../../consensus/epochs" }
sc-transaction-pool = { version = "16.0.0", path = "../../transaction-pool" }
sc-transaction-pool-api = { version = "16.0.0", path = "../../../client/transaction-pool/api" }
sp-api = { version = "14.0.0", path = "../../../primitives/api" }
sp-blockchain = { version = "16.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.20.0", path = "../../../primitives/consensus/common" }
sp-consensus-aura = { version = "0.20.0", path = "../../../primitives/consensus/aura" }
sp-consensus-babe = { version = "0.20.0", path = "../../../primitives/consensus/babe" }
sp-consensus-slots = { version = "0.20.0", path = "../../../primitives/consensus/slots" }
sp-core = { version = "16.0.0", path = "../../../primitives/core" }
sp-inherents = { version = "14.0.0", path = "../../../primitives/inherents" }
sp-keystore = { version = "0.22.0", path = "../../../primitives/keystore" }
sp-runtime = { version = "18.0.0", path = "../../../primitives/runtime" }
sp-timestamp = { version = "14.0.0", path = "../../../primitives/timestamp" }

[dev-dependencies]
tokio = { version = "1.22.0", features = ["rt-multi-thread", "macros"] }
sc-basic-authorship = { version = "0.22.0", path = "../../basic-authorship" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" }
substrate-test-runtime-transaction-pool = { version = "2.0.0", path = "../../../test-utils/runtime/transaction-pool" }
