[package]
name = "pallet-nomination-pools-benchmarking"
version = "14.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME nomination pools pallet benchmarking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# parity
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

# FRAME
frame-benchmarking = { version = "16.0.0", default-features = false, path = "../../benchmarking" }
frame-election-provider-support = { version = "16.0.0", default-features = false, path = "../../election-provider-support" }
frame-support = { version = "16.0.0", default-features = false, path = "../../support" }
frame-system = { version = "16.0.0", default-features = false, path = "../../system" }
pallet-bags-list = { version = "15.0.0", default-features = false, path = "../../bags-list" }
pallet-staking = { version = "16.0.0", default-features = false, path = "../../staking" }
pallet-nomination-pools = { version = "13.0.0", default-features = false, path = "../" }

# Substrate Primitives
sp-runtime = { version = "18.0.0", default-features = false, path = "../../../primitives/runtime" }
sp-runtime-interface = { version = "13.0.0", default-features = false, path = "../../../primitives/runtime-interface" }
sp-staking = { version = "14.0.0", default-features = false, path = "../../../primitives/staking" }
sp-std = { version = "6.0.0", default-features = false, path = "../../../primitives/std" }

[dev-dependencies]
pallet-balances = { version = "16.0.0", default-features = false, path = "../../balances" }
pallet-timestamp = { version = "15.0.0", path = "../../timestamp" }
pallet-staking-reward-curve = { version = "4.0.0", path = "../../staking/reward-curve" }
sp-core = { version = "16.0.0", path = "../../../primitives/core" }
sp-io = { version = "17.0.0", path = "../../../primitives/io" }

[features]
default = ["std"]

std = [
	"frame-benchmarking/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-bags-list/std",
	"pallet-staking/std",
	"pallet-nomination-pools/std",
	"sp-runtime/std",
	"sp-runtime-interface/std",
	"sp-staking/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"frame-election-provider-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-nomination-pools/runtime-benchmarks",
	"pallet-bags-list/runtime-benchmarks",
]
