[package]
name = "pallet-nomination-pools"
version = "13.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME nomination pools pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# parity
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

# FRAME
frame-support = { version = "16.0.0", default-features = false, path = "../support" }
frame-system = { version = "16.0.0", default-features = false, path = "../system" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../../primitives/runtime" }
sp-std = { version = "6.0.0", default-features = false, path = "../../primitives/std" }
sp-staking = { version = "14.0.0", default-features = false, path = "../../primitives/staking" }
sp-core = { version = "16.0.0", default-features = false, path = "../../primitives/core" }
sp-io = { version = "17.0.0", default-features = false, path = "../../primitives/io" }
log = { version = "0.4.0", default-features = false }

# Optional: use for testing and/or fuzzing
pallet-balances = { version = "16.0.0", path = "../balances", optional = true }
sp-tracing = { version = "8.0.0", path = "../../primitives/tracing", optional = true }

[dev-dependencies]
pallet-balances = { version = "16.0.0", path = "../balances" }
sp-tracing = { version = "8.0.0", path = "../../primitives/tracing" }

[features]
default = ["std"]
fuzzing = ["pallet-balances", "sp-tracing"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
	"sp-staking/std",
	"sp-core/std",
	"log/std",
]
runtime-benchmarks = [
	"sp-staking/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime"
]
