[package]
name = "pallet-authority-discovery"
version = "16.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for authority discovery"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
frame-support = { version = "16.0.0", default-features = false, path = "../support" }
frame-system = { version = "16.0.0", default-features = false, path = "../system" }
pallet-session = { version = "16.0.0", default-features = false, features = [
	"historical",
], path = "../session" }
sp-application-crypto = { version = "17.0.0", default-features = false, path = "../../primitives/application-crypto" }
sp-authority-discovery = { version = "14.0.0", default-features = false, path = "../../primitives/authority-discovery" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../../primitives/runtime" }
sp-std = { version = "6.0.0", default-features = false, path = "../../primitives/std" }

[dev-dependencies]
sp-core = { version = "16.0.0", path = "../../primitives/core" }
sp-io = { version = "17.0.0", path = "../../primitives/io" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-session/std",
	"scale-info/std",
	"sp-application-crypto/std",
	"sp-authority-discovery/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = ["frame-support/try-runtime"]
