[package]
description = "Substrate light network protocol"
name = "sc-network-light"
version = "0.21.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-network-light"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = "0.11"

[dependencies]
array-bytes = "4.1"
codec = { package = "parity-scale-codec", version = "3.2.2", features = [
    "derive",
] }
futures = "0.3.21"
libp2p = "0.50.0"
log = "0.4.16"
prost = "0.11"
sp-blockchain = { version = "16.0.0", path = "../../../primitives/blockchain" }
sc-client-api = { version = "16.0.0", path = "../../api" }
sc-network-common = { version = "0.21.0", path = "../common" }
sc-peerset = { version = "6.0.0", path = "../../peerset" }
sp-core = { version = "16.0.0", path = "../../../primitives/core" }
sp-runtime = { version = "18.0.0", path = "../../../primitives/runtime" }
thiserror = "1.0"
