[package]
description = "Substrate sync network protocol"
name = "sc-network-sync"
version = "0.21.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-network-sync"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = "0.11"

[dependencies]
array-bytes = "4.1"
async-trait = "0.1.58"
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }
futures = "0.3.21"
libp2p = "0.50.0"
log = "0.4.17"
lru = "0.8.1"
mockall = "0.11.3"
prost = "0.11"
smallvec = "1.8.0"
thiserror = "1.0"
fork-tree = { version = "5.0.0", path = "../../../utils/fork-tree" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.11.0", path = "../../../utils/prometheus" }
sc-client-api = { version = "16.0.0", path = "../../api" }
sc-consensus = { version = "0.21.0", path = "../../consensus/common" }
sc-network-common = { version = "0.21.0", path = "../common" }
sc-peerset = { version = "6.0.0", path = "../../peerset" }
sc-utils = { version = "5.0.0", path = "../../utils" }
sp-arithmetic = { version = "12.0.0", path = "../../../primitives/arithmetic" }
sp-blockchain = { version = "16.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.20.0", path = "../../../primitives/consensus/common" }
sp-core = { version = "16.0.0", path = "../../../primitives/core" }
sp-finality-grandpa = { version = "14.0.0", path = "../../../primitives/finality-grandpa" }
sp-runtime = { version = "18.0.0", path = "../../../primitives/runtime" }

[dev-dependencies]
tokio = { version = "1.22.0", features = ["macros"] }
quickcheck = { version = "1.0.3", default-features = false }
sc-block-builder = { version = "0.21.0", path = "../../block-builder" }
sp-test-primitives = { version = "2.0.0", path = "../../../primitives/test-primitives" }
sp-tracing = { version = "8.0.0", path = "../../../primitives/tracing" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" }
