[package]
name = "pallet-referenda"
version = "16.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for inclusive on-chain decisions"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
assert_matches = { version = "1.5", optional = true }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"], optional = true }
sp-arithmetic = { version = "12.0.0", default-features = false, path = "../../primitives/arithmetic" }
frame-benchmarking = { version = "16.0.0", default-features = false, optional = true, path = "../benchmarking" }
frame-support = { version = "16.0.0", default-features = false, path = "../support" }
frame-system = { version = "16.0.0", default-features = false, path = "../system" }
sp-io = { version = "17.0.0", default-features = false, path = "../../primitives/io" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../../primitives/runtime" }
sp-std = { version = "6.0.0", default-features = false, path = "../../primitives/std" }
log = { version = "0.4.17", default-features = false }

[dev-dependencies]
assert_matches = { version = "1.5" }
pallet-balances = { version = "16.0.0", path = "../balances" }
pallet-preimage = { version = "16.0.0", path = "../preimage" }
pallet-scheduler = { version = "17.0.0", path = "../scheduler" }
sp-core = { version = "16.0.0", path = "../../primitives/core" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-arithmetic/std",
	"frame-system/std",
	"scale-info/std",
	"serde",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"assert_matches",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
