[package]
name = "pallet-offences-benchmarking"
version = "16.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME offences pallet benchmarking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "16.0.0", default-features = false, path = "../../benchmarking" }
frame-election-provider-support = { version = "16.0.0", default-features = false, path = "../../election-provider-support" }
frame-support = { version = "16.0.0", default-features = false, path = "../../support" }
frame-system = { version = "16.0.0", default-features = false, path = "../../system" }
pallet-babe = { version = "16.0.0", default-features = false, path = "../../babe" }
pallet-balances = { version = "16.0.0", default-features = false, path = "../../balances" }
pallet-grandpa = { version = "16.0.0", default-features = false, path = "../../grandpa" }
pallet-im-online = { version = "15.0.0", default-features = false, path = "../../im-online" }
pallet-offences = { version = "15.0.0", default-features = false, path = "../../offences" }
pallet-session = { version = "16.0.0", default-features = false, path = "../../session" }
pallet-staking = { version = "16.0.0", default-features = false, path = "../../staking" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../../../primitives/runtime" }
sp-staking = { version = "14.0.0", default-features = false, path = "../../../primitives/staking" }
sp-std = { version = "6.0.0", default-features = false, path = "../../../primitives/std" }
log = { version = "0.4.17", default-features = false }

[dev-dependencies]
pallet-staking-reward-curve = { version = "4.0.0", path = "../../staking/reward-curve" }
pallet-timestamp = { version = "15.0.0", path = "../../timestamp" }
sp-core = { version = "16.0.0", path = "../../../primitives/core" }
sp-io = { version = "17.0.0", path = "../../../primitives/io" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-std/std",
	"log/std",
]

runtime-benchmarks = [
	"pallet-staking/runtime-benchmarks",
]
