[package]
name = "node-rpc"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node rpc methods."
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["server"] }
node-primitives = { version = "2.0.0", path = "../primitives" }
pallet-transaction-payment-rpc = { version = "18.0.0", path = "../../../frame/transaction-payment/rpc/" }
mmr-rpc = { version = "16.0.0", path = "../../../client/merkle-mountain-range/rpc/" }
sc-chain-spec = { version = "15.0.0", path = "../../../client/chain-spec" }
sc-client-api = { version = "16.0.0", path = "../../../client/api" }
sc-consensus-babe = { version = "0.22.0", path = "../../../client/consensus/babe" }
sc-consensus-babe-rpc = { version = "0.22.0", path = "../../../client/consensus/babe/rpc" }
sc-consensus-epochs = { version = "0.21.0", path = "../../../client/consensus/epochs" }
sc-finality-grandpa = { version = "0.22.0", path = "../../../client/finality-grandpa" }
sc-finality-grandpa-rpc = { version = "0.23.0", path = "../../../client/finality-grandpa/rpc" }
sc-rpc = { version = "17.0.0", path = "../../../client/rpc" }
sc-rpc-api = { version = "0.21.0", path = "../../../client/rpc-api" }
sc-rpc-spec-v2 = { version = "0.22.0", path = "../../../client/rpc-spec-v2" }
sc-sync-state-rpc = { version = "0.22.0", path = "../../../client/sync-state-rpc" }
sc-transaction-pool-api = { version = "16.0.0", path = "../../../client/transaction-pool/api" }
sp-api = { version = "14.0.0", path = "../../../primitives/api" }
sp-block-builder = { version = "14.0.0", path = "../../../primitives/block-builder" }
sp-blockchain = { version = "16.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.20.0", path = "../../../primitives/consensus/common" }
sp-consensus-babe = { version = "0.20.0", path = "../../../primitives/consensus/babe" }
sp-keystore = { version = "0.22.0", path = "../../../primitives/keystore" }
sp-runtime = { version = "18.0.0", path = "../../../primitives/runtime" }
substrate-frame-rpc-system = { version = "16.0.0", path = "../../../utils/frame/rpc/system" }
substrate-state-trie-migration-rpc = { version = "15.0.0", path = "../../../utils/frame/rpc/state-trie-migration-rpc/" }
