[package]
name = "sc-authority-discovery"
version = "0.22.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate authority discovery."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = "0.11"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
futures = "0.3.21"
futures-timer = "3.0.1"
ip_network = "0.4.1"
libp2p = { version = "0.50.0", features = ["kad"] }
log = "0.4.17"
prost = "0.11"
rand = "0.8.5"
thiserror = "1.0"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.11.0", path = "../../utils/prometheus" }
sc-client-api = { version = "16.0.0", path = "../api" }
sc-network-common = { version = "0.21.0", path = "../network/common" }
sp-api = { version = "14.0.0", path = "../../primitives/api" }
sp-authority-discovery = { version = "14.0.0", path = "../../primitives/authority-discovery" }
sp-blockchain = { version = "16.0.0", path = "../../primitives/blockchain" }
sp-core = { version = "16.0.0", path = "../../primitives/core" }
sp-keystore = { version = "0.22.0", path = "../../primitives/keystore" }
sp-runtime = { version = "18.0.0", path = "../../primitives/runtime" }
async-trait = "0.1.56"

[dev-dependencies]
quickcheck = { version = "1.0.3", default-features = false }
sp-tracing = { version = "8.0.0", path = "../../primitives/tracing" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../test-utils/runtime/client" }
