[package]
name = "sp-consensus-aura"
version = "0.20.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.57", optional = true }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
sp-api = { version = "14.0.0", default-features = false, path = "../../api" }
sp-application-crypto = { version = "17.0.0", default-features = false, path = "../../application-crypto" }
sp-consensus = { version = "0.20.0", optional = true, path = "../common" }
sp-consensus-slots = { version = "0.20.0", default-features = false, path = "../slots" }
sp-inherents = { version = "14.0.0", default-features = false, path = "../../inherents" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../../runtime" }
sp-std = { version = "6.0.0", default-features = false, path = "../../std" }
sp-timestamp = { version = "14.0.0", default-features = false, path = "../../timestamp" }

[features]
default = ["std"]
std = [
	"async-trait",
	"codec/std",
	"scale-info/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-consensus",
	"sp-consensus-slots/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-timestamp/std",
]
