[package]
name = "frame-executive"
version = "16.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME executives engine"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
frame-support = { version = "16.0.0", default-features = false, path = "../support" }
frame-system = { version = "16.0.0", default-features = false, path = "../system" }
frame-try-runtime = { version = "0.22.0", default-features = false, path = "../try-runtime", optional = true }
sp-core = { version = "16.0.0", default-features = false, path = "../../primitives/core" }
sp-io = { version = "17.0.0", default-features = false, path = "../../primitives/io" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../../primitives/runtime" }
sp-std = { version = "6.0.0", default-features = false, path = "../../primitives/std" }
sp-tracing = { version = "8.0.0", default-features = false, path = "../../primitives/tracing" }

[dev-dependencies]
array-bytes = "4.1"
pallet-balances = { version = "16.0.0", path = "../balances" }
pallet-transaction-payment = { version = "16.0.0", path = "../transaction-payment" }
sp-core = { version = "16.0.0", path = "../../primitives/core" }
sp-inherents = { version = "14.0.0", path = "../../primitives/inherents" }
sp-io = { version = "17.0.0", path = "../../primitives/io" }
sp-version = { version = "16.0.0", path = "../../primitives/version" }

[features]
default = ["std"]
with-tracing = ["sp-tracing/with-tracing"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-tracing/std",
]
try-runtime = ["frame-support/try-runtime", "frame-try-runtime/try-runtime", "sp-runtime/try-runtime"]
