[package]
name = "sc-consensus-aura"
version = "0.22.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Aura consensus algorithm for substrate"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.57"
codec = { package = "parity-scale-codec", version = "3.2.2" }
futures = "0.3.21"
log = "0.4.17"
thiserror = "1.0"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.11.0", path = "../../../utils/prometheus" }
sc-block-builder = { version = "0.21.0", path = "../../block-builder" }
sc-client-api = { version = "16.0.0", path = "../../api" }
sc-consensus = { version = "0.21.0", path = "../../../client/consensus/common" }
sc-consensus-slots = { version = "0.21.0", path = "../slots" }
sc-telemetry = { version = "6.0.0", path = "../../telemetry" }
sp-api = { version = "14.0.0", path = "../../../primitives/api" }
sp-application-crypto = { version = "17.0.0", path = "../../../primitives/application-crypto" }
sp-block-builder = { version = "14.0.0", path = "../../../primitives/block-builder" }
sp-blockchain = { version = "16.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.20.0", path = "../../../primitives/consensus/common" }
sp-consensus-aura = { version = "0.20.0", path = "../../../primitives/consensus/aura" }
sp-consensus-slots = { version = "0.20.0", path = "../../../primitives/consensus/slots" }
sp-core = { version = "16.0.0", path = "../../../primitives/core" }
sp-inherents = { version = "14.0.0", path = "../../../primitives/inherents" }
sp-keystore = { version = "0.22.0", path = "../../../primitives/keystore" }
sp-runtime = { version = "18.0.0", path = "../../../primitives/runtime" }

[dev-dependencies]
parking_lot = "0.12.1"
tempfile = "3.1.0"
sc-keystore = { version = "13.0.0", path = "../../keystore" }
sc-network = { version = "0.22.0", path = "../../network" }
sc-network-test = { version = "0.8.0", path = "../../network/test" }
sp-keyring = { version = "18.0.0", path = "../../../primitives/keyring" }
sp-timestamp = { version = "14.0.0", path = "../../../primitives/timestamp" }
sp-tracing = { version = "8.0.0", path = "../../../primitives/tracing" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" }
tokio = { version = "1.22.0" }
