[package]
name = "node-bench"
version = "0.9.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node integration benchmarks."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-bytes = "4.1"
clap = { version = "4.0.9", features = ["derive"] }
log = "0.4.17"
node-primitives = { version = "2.0.0", path = "../primitives" }
node-testing = { version = "3.0.0-dev", path = "../testing" }
kitchensink-runtime = { version = "3.0.0-dev", path = "../runtime" }
sc-client-api = { version = "16.0.0", path = "../../../client/api/" }
sp-runtime = { version = "18.0.0", path = "../../../primitives/runtime" }
sp-state-machine = { version = "0.22.0", path = "../../../primitives/state-machine" }
serde = "1.0.136"
serde_json = "1.0.85"
derive_more = { version = "0.99.17", default-features = false, features = ["display"] }
kvdb = "0.13.0"
kvdb-rocksdb = "0.17.0"
sp-trie = { version = "16.0.0", path = "../../../primitives/trie" }
sp-core = { version = "16.0.0", path = "../../../primitives/core" }
sp-consensus = { version = "0.20.0", path = "../../../primitives/consensus/common" }
sc-basic-authorship = { version = "0.22.0", path = "../../../client/basic-authorship" }
sp-inherents = { version = "14.0.0", path = "../../../primitives/inherents" }
sp-timestamp = { version = "14.0.0", default-features = false, path = "../../../primitives/timestamp" }
sp-tracing = { version = "8.0.0", path = "../../../primitives/tracing" }
hash-db = "0.15.2"
tempfile = "3.1.0"
fs_extra = "1"
rand = { version = "0.8.5", features = ["small_rng"] }
lazy_static = "1.4.0"
parity-db = "0.4.3"
sc-transaction-pool = { version = "16.0.0", path = "../../../client/transaction-pool" }
sc-transaction-pool-api = { version = "16.0.0", path = "../../../client/transaction-pool/api" }
futures = { version = "0.3.21", features = ["thread-pool"] }
