[package]
name = "pallet-root-offences"
version = "13.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME root offences pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

pallet-session = { version = "16.0.0", features = [ "historical" ], path = "../../frame/session", default-features = false }
pallet-staking = { version = "16.0.0", default-features = false, path = "../../frame/staking" }

frame-support = { version = "16.0.0", default-features = false, path = "../support" }
frame-system = { version = "16.0.0", default-features = false, path = "../system" }
sp-runtime = { version = "18.0.0", path = "../../primitives/runtime" }
sp-staking = { version = "14.0.0", default-features = false, path = "../../primitives/staking" }

[dev-dependencies]
pallet-balances = { version = "16.0.0", path = "../balances" }
pallet-timestamp = { version = "15.0.0", path = "../timestamp" }
pallet-staking-reward-curve = { version = "4.0.0", path = "../staking/reward-curve" }

sp-core = { version = "16.0.0", path = "../../primitives/core" }
sp-io = { version = "17.0.0", default-features = false, path = "../../primitives/io" }
sp-std = { version = "6.0.0", default-features = false, path = "../../primitives/std" }

frame-election-provider-support = { version = "16.0.0", path = "../election-provider-support" }

[features]
runtime-benchmarks = []
try-runtime = ["frame-support/try-runtime"]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
    "frame-system/std",
	"pallet-session/std",
	"pallet-staking/std",
	"scale-info/std",
	"sp-runtime/std",
]
