[package]
description = "Substrate transaction protocol"
name = "sc-network-transactions"
version = "0.21.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-network-transactions"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = "4.1"
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }
futures = "0.3.21"
libp2p = "0.50.0"
log = "0.4.17"
pin-project = "1.0.12"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.11.0", path = "../../../utils/prometheus" }
sc-network-common = { version = "0.21.0", path = "../common" }
sc-peerset = { version = "6.0.0", path = "../../peerset" }
sc-utils = { version = "5.0.0", path = "../../utils" }
sp-runtime = { version = "18.0.0", path = "../../../primitives/runtime" }
sp-consensus = { version = "0.20.0", path = "../../../primitives/consensus/common" }
