[package]
name = "sp-finality-grandpa"
version = "14.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Primitives for GRANDPA integration, suitable for WASM compilation."
documentation = "https://docs.rs/sp-finality-grandpa"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
grandpa = { package = "finality-grandpa", version = "0.16.1", default-features = false, features = ["derive-codec"] }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"], optional = true }
sp-api = { version = "14.0.0", default-features = false, path = "../api" }
sp-application-crypto = { version = "17.0.0", default-features = false, path = "../application-crypto" }
sp-core = { version = "16.0.0", default-features = false, path = "../core" }
sp-keystore = { version = "0.22.0", default-features = false, optional = true, path = "../keystore" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../runtime" }
sp-std = { version = "6.0.0", default-features = false, path = "../std" }

[features]
default = ["std"]
std = [
	"codec/std",
	"grandpa/std",
	"log/std",
	"scale-info/std",
	"serde",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-keystore",
	"sp-runtime/std",
	"sp-std/std",
]
