[package]
name = "pallet-transaction-payment-rpc-runtime-api"
version = "16.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "RPC runtime API for transaction payment FRAME pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
pallet-transaction-payment = { version = "16.0.0", default-features = false, path = "../../../transaction-payment" }
sp-api = { version = "14.0.0", default-features = false, path = "../../../../primitives/api" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../../../../primitives/runtime" }
sp-weights = { version = "14.0.0", default-features = false, path = "../../../../primitives/weights" }

[features]
default = ["std"]
std = [
	"codec/std",
	"pallet-transaction-payment/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-weights/std",
]
