[package]
name = "pallet-example-basic"
version = "15.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Unlicense"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME example pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "16.0.0", default-features = false, optional = true, path = "../../benchmarking" }
frame-support = { version = "16.0.0", default-features = false, path = "../../support" }
frame-system = { version = "16.0.0", default-features = false, path = "../../system" }
pallet-balances = { version = "16.0.0", default-features = false, path = "../../balances" }
sp-io = { version = "17.0.0", default-features = false, path = "../../../primitives/io" }
sp-runtime = { version = "18.0.0", default-features = false, path = "../../../primitives/runtime" }
sp-std = { version = "6.0.0", default-features = false, path = "../../../primitives/std" }

[dev-dependencies]
sp-core = { version = "16.0.0", default-features = false, path = "../../../primitives/core" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-balances/std",
	"scale-info/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
