[package]
name = "substrate-rpc-client"
version = "0.21.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Shared JSON-RPC client"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["ws-client"] }
sc-rpc-api = { version = "0.21.0", path = "../../../../client/rpc-api" }
async-trait = "0.1.57"
serde = "1"
sp-runtime = { version = "18.0.0", path = "../../../../primitives/runtime" }
log = "0.4"

[dev-dependencies]
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread", "sync"] }
sp-core = { path = "../../../../primitives/core" , version = "16.0.0" }
