[package]
name = "mmr-rpc"
version = "16.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Node-specific RPC methods for interaction with Merkle Mountain Range pallet."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
serde = { version = "1.0.136", features = ["derive"] }
sp-api = { version = "14.0.0", path = "../../../primitives/api" }
sp-blockchain = { version = "16.0.0", path = "../../../primitives/blockchain" }
sp-core = { version = "16.0.0", path = "../../../primitives/core" }
sp-mmr-primitives = { version = "14.0.0", path = "../../../primitives/merkle-mountain-range" }
sp-runtime = { version = "18.0.0", path = "../../../primitives/runtime" }
anyhow = "1"

[dev-dependencies]
serde_json = "1.0.85"
